from pathlib import Path
import sys

path = Path(sys.argv[1])
text = path.read_text(encoding='utf-8')

def replace_once(old, new, label):
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected exactly 1 occurrence, found {count}')
    text = text.replace(old, new, 1)

replace_once('Orbis Watch OTA 5610 v3.21', 'Orbis Watch OTA 5610 v3.22', 'title')
replace_once(
    'A v3.21 acrescenta o intérprete recuperado do HryFine 3.8.9, consultas de recursos/lembretes e prévia local do RTC, sem alterar hora, RTC ou firmware; handshake e identidade continuam manuais.',
    'A v3.22 corrige o parser de ACK FD e audita o schema bin_list devolvido pelo servidor, sem baixar BIN, sem alterar hora, RTC ou firmware; handshake e identidade continuam manuais.',
    'transition note'
)
replace_once(
    'Button serverMetadata = button("2. Consultar servidor oficial — somente metadados");',
    'Button serverMetadata = button("2. Consultar servidor e auditar bin_list — sem download");',
    'server button'
)

old_buttons = '''        Button hryProtocolMap = button("21. Mostrar mapa HryFine recuperado — local");
        hryProtocolMap.setOnClickListener(v -> appendHryFineProtocolMap());
        content.addView(hryProtocolMap, marginLayout(0, 2, 0, 3));
'''
new_buttons = '''        Button hryProtocolMap = button("21. Mostrar mapa HryFine recuperado — local");
        hryProtocolMap.setOnClickListener(v -> appendHryFineProtocolMap());
        content.addView(hryProtocolMap, marginLayout(0, 2, 0, 2));

        Button binListSchema = button("22. Explicar bin_list do HryFine — local");
        binListSchema.setOnClickListener(v -> appendBinListSchema());
        content.addView(binListSchema, marginLayout(0, 2, 0, 8));
'''
replace_once(old_buttons, new_buttons, 'button insertion')

old_parse_head = '''    private void parseNusFrame(byte[] frame) {
        if (frame.length < 5) return;
        int prefix = frame[0] & 0xFF;
        int command = frame[4] & 0xFF;
        int key = frame.length > 6 ? frame[6] & 0xFF : -1;
        append(String.format(Locale.US, "  ↳ NUS COMPLETO %02X comando=0x%02X key=0x%02X len=%d ASCII=\\\"%s\\\"",
                prefix, command, key, frame.length, printableAscii(frame)));
        appendHryFineFrameValidation(frame, prefix, command, key);
'''
new_parse_head = '''    private void parseNusFrame(byte[] frame) {
        if (frame.length < 5) return;
        int prefix = frame[0] & 0xFF;
        int command = frame[4] & 0xFF;
        // DF carries the key/action at offset 6. FD is a compact ACK generated by
        // AckPackageConfigUtils: command@4, original key@5, opaque meta@6..7, status@8.
        int key = prefix == 0xFD
                ? (frame.length > 5 ? frame[5] & 0xFF : -1)
                : (frame.length > 6 ? frame[6] & 0xFF : -1);
        append(String.format(Locale.US, "  ↳ NUS COMPLETO %02X comando=0x%02X key=0x%02X len=%d ASCII=\\\"%s\\\"",
                prefix, command, key, frame.length, printableAscii(frame)));
        appendHryFineFrameValidation(frame, prefix, command, key);
'''
replace_once(old_parse_head, new_parse_head, 'parseNusFrame head')

replace_once(
    '''        byte[] genericPayload = frame.length > 9
                ? java.util.Arrays.copyOfRange(frame, 9, frame.length)
                : new byte[0];''',
    '''        byte[] genericPayload = prefix == 0xDF && frame.length > 9
                ? java.util.Arrays.copyOfRange(frame, 9, frame.length)
                : new byte[0];''',
    'generic payload guard'
)

old_validation = '''    private void appendHryFineFrameValidation(byte[] frame, int prefix, int command, int key) {
        int declaredBody = frame.length >= 3 ? ((frame[1] & 0xFF) << 8) | (frame[2] & 0xFF) : -1;
        int declaredPayload = frame.length >= 9 ? ((frame[7] & 0xFF) << 8) | (frame[8] & 0xFF) : -1;
        int sum = 0;
        for (int i = 0; i < frame.length; i++) if (i != 3) sum = (sum + (frame[i] & 0xFF)) & 0xFF;
        boolean checksumOk = frame.length > 3 && sum == (frame[3] & 0xFF);
        boolean bodyOk = declaredBody >= 0 && frame.length == 4 + declaredBody;
        boolean payloadOk = declaredPayload < 0 || frame.length == 9 + declaredPayload;
        append("  ↳ HRYFINE FRAME: " + hryFineCommandName(command)
                + " prefix=" + String.format(Locale.US, "%02X", prefix)
                + " key=" + String.format(Locale.US, "%02X", key)
                + " checksum=" + checksumOk + " body_len=" + bodyOk + " payload_len=" + payloadOk
                + " declared_payload=" + declaredPayload);
    }
'''
new_validation = '''    private void appendHryFineFrameValidation(byte[] frame, int prefix, int command, int key) {
        int declaredBody = frame.length >= 3 ? ((frame[1] & 0xFF) << 8) | (frame[2] & 0xFF) : -1;
        int sum = 0;
        for (int i = 0; i < frame.length; i++) if (i != 3) sum = (sum + (frame[i] & 0xFF)) & 0xFF;
        boolean checksumOk = frame.length > 3 && sum == (frame[3] & 0xFF);
        boolean bodyOk = declaredBody >= 0 && frame.length == 4 + declaredBody;

        if (prefix == 0xFD) {
            int ackKey = frame.length > 5 ? frame[5] & 0xFF : -1;
            int ackMeta = frame.length > 7 ? ((frame[6] & 0xFF) << 8) | (frame[7] & 0xFF) : -1;
            int ackStatus = frame.length > 8 ? frame[8] & 0xFF : -1;
            boolean ackShape = frame.length == 9 && declaredBody == 5;
            append("  ↳ HRYFINE ACK: " + hryFineCommandName(command)
                    + " prefix=FD key=" + String.format(Locale.US, "%02X", ackKey)
                    + " checksum=" + checksumOk + " body_len=" + bodyOk + " ack_shape=" + ackShape
                    + " meta_opaque=" + (ackMeta < 0 ? "-" : String.format(Locale.US, "0x%04X", ackMeta))
                    + " status=" + ackStatus + "(" + hryFineAckStatus(ackStatus) + ")");
            return;
        }

        int declaredPayload = frame.length >= 9 ? ((frame[7] & 0xFF) << 8) | (frame[8] & 0xFF) : -1;
        boolean payloadOk = declaredPayload < 0 || frame.length == 9 + declaredPayload;
        append("  ↳ HRYFINE FRAME: " + hryFineCommandName(command)
                + " prefix=" + String.format(Locale.US, "%02X", prefix)
                + " key=" + String.format(Locale.US, "%02X", key)
                + " checksum=" + checksumOk + " body_len=" + bodyOk + " payload_len=" + payloadOk
                + " declared_payload=" + declaredPayload);
    }

    private String hryFineAckStatus(int status) {
        if (status == 1) return "sucesso";
        if (status < 0) return "ausente";
        return "não-sucesso/valor desconhecido";
    }
'''
replace_once(old_validation, new_validation, 'ACK parser')

old_map_end = '''        append("OTA: D5/0F e D5/01 confirmados. 0x03 partições, firmware, checksums, finalização e reboot continuam bloqueados.");
        append("OBJETIVO: relógio/RTC + BLE manutenção + DOOM + saída segura, sem abrir o relógio.");
        append("===== FIM MAPA HRYFINE =====");
    }
'''
new_map_end = '''        append("OTA: D5/0F e D5/01 confirmados. 0x03 partições, firmware, checksums, finalização e reboot continuam bloqueados.");
        append("BIN_LIST: o APK contém o modelo/parser e o endpoint, mas não contém a lista concreta nem os BINs do G28; a lista chega dinamicamente do servidor.");
        append("ACK FD: formato compacto command@4, key@5, meta opaco@6..7 e status@8; status 1 é sucesso no HryFine.");
        append("OBJETIVO: relógio/RTC + BLE manutenção + DOOM + saída segura, sem abrir o relógio.");
        append("===== FIM MAPA HRYFINE =====");
    }

    private void appendBinListSchema() {
        append("===== BIN_LIST DO HRYFINE — ESTRUTURA LOCAL =====");
        append("O APK não carrega um manifesto real do G28. Ele carrega apenas a classe OtaUpdateInfo.bin_list e o código que consulta o servidor.");
        append("Endpoint oficial: ota.lianhezhuli.com/api/hry/get_update; parâmetro central=unique_code autenticado por assinatura MD5 do app.");
        append("Campos por item: id, hry_id, part_id, part_addr, part_len, bin_file, bin_size, status, is_force, is_test, is_white.");
        append("Fluxo oficial: resposta não vazia → ordenar por part_id → baixar cada bin_file para files/ota → criar OtaBean(part_id,path,id) → montar tabela 0x03.");
        append("Nenhum BIN de firmware do G28 está embutido no HryFine exportado. O único arquivo .bin encontrado é DebugProbesKt.bin, recurso interno do Kotlin e não firmware.");
        append("Na resposta já observada para o unique_code do G28, o servidor autenticou, mas não publicou bin_list; portanto não existe endereço/partição genuíno para usar ainda.");
        append("A v3.22 apenas audita os metadados caso apareçam. Não baixa arquivos e não transmite tabela de partições.");
        append("===== FIM BIN_LIST =====");
    }
'''
replace_once(old_map_end, new_map_end, 'binlist local schema')

old_server_bins = '''                if (bins != null) {
                    append("SERVER VALIDADO: bin_list=" + bins.length()
                            + " updateAvailable=" + officialUpdateAvailable);
                    setStatus(officialUpdateAvailable
                            ? "Servidor confirmou pacote OTA. Passo 3 liberado."
                            : "Servidor autenticou a consulta, mas não há BIN de atualização.");
'''
new_server_bins = '''                if (bins != null) {
                    append("SERVER VALIDADO: bin_list=" + bins.length()
                            + " updateAvailable=" + officialUpdateAvailable);
                    auditBinList(bins);
                    setStatus(officialUpdateAvailable
                            ? "Servidor confirmou metadados OTA; download e gravação continuam bloqueados."
                            : "Servidor autenticou a consulta, mas não há BIN de atualização.");
'''
replace_once(old_server_bins, new_server_bins, 'server audit call')

insert_anchor = '''    private JSONArray findBinList(Object node) throws JSONException {
'''
audit_methods = '''    private void auditBinList(JSONArray bins) {
        append("===== AUDITORIA BIN_LIST — SEM DOWNLOAD =====");
        if (bins == null) {
            append("bin_list ausente.");
            append("===== FIM AUDITORIA BIN_LIST =====");
            return;
        }
        if (bins.length() == 0) {
            append("bin_list presente, porém vazio.");
            append("===== FIM AUDITORIA BIN_LIST =====");
            return;
        }

        long totalBin = 0;
        long totalPartition = 0;
        boolean allSchemaComplete = true;
        boolean allSizesFit = true;
        boolean allPartIdsValid = true;
        List<long[]> ranges = new ArrayList<>();

        for (int i = 0; i < bins.length(); i++) {
            JSONObject item = bins.optJSONObject(i);
            if (item == null) {
                append("item[" + i + "] não é objeto JSON");
                allSchemaComplete = false;
                continue;
            }
            long id = item.optLong("id", -1);
            long hryId = item.optLong("hry_id", -1);
            long partId = item.optLong("part_id", -1);
            long partAddr = unsigned32(item.optLong("part_addr", -1));
            long partLen = unsigned32(item.optLong("part_len", -1));
            long binSize = unsigned32(item.optLong("bin_size", -1));
            long status = item.optLong("status", -1);
            long isForce = item.optLong("is_force", -1);
            long isTest = item.optLong("is_test", -1);
            long isWhite = item.optLong("is_white", -1);
            String binFile = item.optString("bin_file", "");

            boolean schemaComplete = id >= 0 && partId >= 0 && partAddr >= 0 && partLen >= 0
                    && binSize >= 0 && !binFile.isEmpty();
            boolean partIdValid = partId >= 0 && partId <= 0xFF;
            boolean sizeFits = partLen <= 0 || binSize <= partLen;
            allSchemaComplete &= schemaComplete;
            allPartIdsValid &= partIdValid;
            allSizesFit &= sizeFits;
            if (binSize > 0) totalBin += binSize;
            if (partLen > 0) totalPartition += partLen;
            if (partAddr >= 0 && partLen > 0) ranges.add(new long[]{partAddr, partAddr + partLen, partId});

            String host = "-";
            String fileName = binFile.isEmpty() ? "-" : fileNameFromUrl(binFile);
            try { host = new URL(binFile).getHost(); } catch (Exception ignored) { }
            append(String.format(Locale.US,
                    "bin[%d] id=%d hry_id=%d part_id=%d addr=0x%08X part_len=%d bin_size=%d status=%d force=%d test=%d white=%d host=%s file=%s schema=%s size_fit=%s",
                    i, id, hryId, partId, partAddr, partLen, binSize, status, isForce, isTest, isWhite,
                    emptyAsDash(host), fileName, schemaComplete, sizeFits));
        }

        Collections.sort(ranges, (a, b) -> Long.compare(a[0], b[0]));
        boolean overlaps = false;
        for (int i = 1; i < ranges.size(); i++) {
            long[] previous = ranges.get(i - 1);
            long[] current = ranges.get(i);
            if (current[0] < previous[1]) {
                overlaps = true;
                append(String.format(Locale.US,
                        "SOBREPOSIÇÃO: part_id=%d termina em 0x%08X e part_id=%d começa em 0x%08X",
                        previous[2], previous[1], current[2], current[0]));
            }
        }
        append("RESUMO bin_count=" + bins.length()
                + " total_bin=" + totalBin
                + " total_partition=" + totalPartition
                + " schema_complete=" + allSchemaComplete
                + " part_ids_valid=" + allPartIdsValid
                + " sizes_fit=" + allSizesFit
                + " overlaps=" + overlaps);
        append("POLÍTICA: metadados apenas; nenhum bin_file foi baixado e nenhum comando 0x03 foi enviado.");
        append("===== FIM AUDITORIA BIN_LIST =====");
    }

    private static long unsigned32(long value) {
        if (value < 0) return value == -1 ? -1 : value & 0xFFFFFFFFL;
        return value;
    }

'''
if insert_anchor not in text:
    raise SystemExit('findBinList anchor not found')
text = text.replace(insert_anchor, audit_methods + insert_anchor, 1)

path.write_text(text, encoding='utf-8')
print('patched', path)
