plugins {
    id 'com.android.application'
}

android {
    namespace 'com.orbiswatchlab'
    compileSdk 35

    defaultConfig {
        applicationId "com.orbiswatchlab"
        minSdk 21
        targetSdk 35
        versionCode 27
        versionName "3.23-historical-binlist-probe"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
